theme="simple"
#baseurl = "https://github.io/pintergreg/"
relativeURLs = true
DefaultContentLanguage = "en"
languageCode = "en"
#enableGitInfo = true
title = "Gergő Pintér"
MetaDataFormat = "toml"
copyright = "2024"


[mediaTypes]
  [mediaTypes.'text/html']
    suffixes = ["html"]
  [mediaTypes.'text/asciidoc']
    suffixes = ["asciidoc"]

[outputFormats]
  [outputFormats.asciidoc]
    isPlainText = true
    mediaType = "text/asciidoc"

[Params]
  github = "pintergreg"
  gitlab = "pintergreg"
  hackerrank = "pintergreg"
  twitter = "pintergreg"
  orcid = "0000-0003-4731-3816"
  researchgate = "Gergo-Pinter"
  linkedin = "gerg%C5%91-pint%C3%A9r-20454667"
  scholar = "801sS3AAAAAJ"


# requires Hugo 0.41 or higher
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 4
    wrapperClass = 'highlight'

