[tool.poetry]
name = "convert-references"
version = "0.1.0"
description = ""
authors = ["pintergreg <pintergreg@gmail.com>"]
readme = "README.md"
packages = [{include = "convert_references"}]

[tool.poetry.dependencies]
python = "^3.10"
rispy = "^0.7.1"
pyaml = "^24.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
