name: CI

on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]
    # pull_request:
    # branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: install stuff
              run: |
                  sudo apt-get install -y hugo ruby ruby-bundler ruby-asciidoctor-pdf ruby-toml-rb snapd
                  bundle config set path 'venv'
                  bundle install
                  sudo snap install typst
            - name: build site
              run: hugo

            - name: generate CV
              env:
                  EMAIL: ${{ secrets.EMAIL }}
              run: |
                  bundle exec ruby generate_cv.rb
                  typst c public/cv/index.typ public/cv.pdf

            - name: build site again to include CV
              run: hugo

            - name: deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./public
